services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\UX\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    # OSW3\UX\Command\BuildCommand:
    #     tags: ['console.command']