<?php 
namespace OSW3\UX\Enum\FormWidget;

use OSW3\UX\Trait\EnumTrait;

enum PhoneCodes: string 
{
    use EnumTrait;
    
    case AF = '+93';  // Afghanistan
    case AL = '+355'; // Albanie
    case DZ = '+213'; // Algérie
    case AD = '+376'; // Andorre
    case AO = '+244'; // Angola
    case AG = '+1-268'; // Antigua-et-Barbuda
    case AR = '+54'; // Argentine
    case AM = '+374'; // Arménie
    case AU = '+61'; // Australie
    case AT = '+43'; // Autriche
    case AZ = '+994'; // Azerbaïdjan
    case BS = '+1-242'; // Bahamas
    case BH = '+973'; // Bahreïn
    case BD = '+880'; // Bangladesh
    case BB = '+1-246'; // Barbade
    case BY = '+375'; // Bélarus
    case BE = '+32'; // Belgique
    case BZ = '+501'; // Belize
    case BJ = '+229'; // Bénin
    case BT = '+975'; // Bhoutan
    case BO = '+591'; // Bolivie
    case BA = '+387'; // Bosnie-Herzégovine
    case BW = '+267'; // Botswana
    case BR = '+55'; // Brésil
    case BN = '+673'; // Brunei
    case BG = '+359'; // Bulgarie
    case BF = '+226'; // Burkina Faso
    case BI = '+257'; // Burundi
    case KH = '+855'; // Cambodge
    case CM = '+237'; // Cameroun
    // case CA = '+1'; // Canada
    case CV = '+238'; // Cap-Vert
    case CL = '+56'; // Chili
    case CN = '+86'; // Chine
    case CO = '+57'; // Colombie
    case KM = '+269'; // Comores
    case CD = '+243'; // Congo, République Démocratique du
    case CG = '+242'; // Congo, République du
    case CR = '+506'; // Costa Rica
    case HR = '+385'; // Croatie
    case CU = '+53'; // Cuba
    case CY = '+357'; // Chypre
    case DK = '+45'; // Danemark
    case DJ = '+253'; // Djibouti
    case DM = '+1-767'; // Dominique
    case EG = '+20'; // Égypte
    case SV = '+503'; // El Salvador
    case EC = '+593'; // Équateur
    case ER = '+291'; // Érythrée
    case ES = '+34'; // Espagne
    case EE = '+372'; // Estonie
    case SZ = '+268'; // Eswatini
    case US = '+1'; // États-Unis
    case ET = '+251'; // Éthiopie
    case FJ = '+679'; // Fidji
    case FI = '+358'; // Finlande
    case FR = '+33'; // France
    case GA = '+241'; // Gabon
    case GM = '+220'; // Gambie
    case GE = '+995'; // Géorgie
    case GH = '+233'; // Ghana
    case GI = '+350'; // Gibraltar
    case GR = '+30'; // Grèce
    case GD = '+1-473'; // Grenade
    case GP = '+590'; // Guadeloupe
    case GU = '+1-671'; // Guam
    case GT = '+502'; // Guatemala
    case GN = '+224'; // Guinée
    case GW = '+245'; // Guinée-Bissau
    case GY = '+592'; // Guyana
    case HT = '+509'; // Haïti
    case HN = '+504'; // Honduras
    case HK = '+852'; // Hong Kong
    case HU = '+36'; // Hongrie
    case IS = '+354'; // Islande
    case IN = '+91'; // Inde
    case ID = '+62'; // Indonésie
    case IQ = '+964'; // Irak
    case IR = '+98'; // Iran
    case IE = '+353'; // Irlande
    case IL = '+972'; // Israël
    case IT = '+39'; // Italie
    case JM = '+1-876'; // Jamaïque
    case JP = '+81'; // Japon
    case JO = '+962'; // Jordanie
    case KZ = '+7'; // Kazakhstan
    case KE = '+254'; // Kenya
    case KG = '+996'; // Kirghizistan
    case KI = '+686'; // Kiribati
    case KW = '+965'; // Koweït
    case LA = '+856'; // Laos
    case LV = '+371'; // Lettonie
    case LB = '+961'; // Liban
    case LR = '+231'; // Libéria
    case LY = '+218'; // Libye
    case LI = '+423'; // Liechtenstein
    case LT = '+370'; // Lituanie
    case LU = '+352'; // Luxembourg
    case MG = '+261'; // Madagascar
    case MY = '+60'; // Malaisie
    case MW = '+265'; // Malawi
    case MV = '+960'; // Maldives
    case ML = '+223'; // Mali
    case MT = '+356'; // Malte
    case MA = '+212'; // Maroc
    case MU = '+230'; // Maurice
    case MR = '+222'; // Mauritanie
    case MX = '+52'; // Mexique
    case MD = '+373'; // Moldavie
    case MC = '+377'; // Monaco
    case MN = '+976'; // Mongolie
    case ME = '+382'; // Monténégro
    case MZ = '+258'; // Mozambique
    case MM = '+95'; // Myanmar (Birmanie)
    case NA = '+264'; // Namibie
    case NR = '+674'; // Nauru
    case NP = '+977'; // Népal
    case NI = '+505'; // Nicaragua
    case NE = '+227'; // Niger
    case NG = '+234'; // Nigéria
    case NU = '+683'; // Niue
    case NO = '+47'; // Norvège
    case NZ = '+64'; // Nouvelle-Zélande
    case OM = '+968'; // Oman
    case PK = '+92'; // Pakistan
    case PW = '+680'; // Palaos
    case PA = '+507'; // Panama
    case PG = '+675'; // Papouasie-Nouvelle-Guinée
    case PY = '+595'; // Paraguay
    case PE = '+51'; // Pérou
    case PH = '+63'; // Philippines
    case PL = '+48'; // Pologne
    case PT = '+351'; // Portugal
    case QA = '+974'; // Qatar
    case CF = '+236'; // République Centrafricaine
    case RE = '+262'; // Réunion
    case RO = '+40'; // Roumanie
    case GB = '+44'; // Royaume-Uni
    case RW = '+250'; // Rwanda
    case KN = '+1-869'; // Saint-Kitts-et-Nevis
    case LC = '+1-758'; // Saint-Lucie
    case VC = '+1-784'; // Saint-Vincent-et-les-Grenadines
    case SM = '+378'; // Saint-Marin
    case ST = '+239'; // São Tomé-et-Principe
    case SN = '+221'; // Sénégal
    case RS = '+381'; // Serbie
    case SC = '+248'; // Seychelles
    case SL = '+232'; // Sierra Leone
    case SG = '+65'; // Singapour
    case SK = '+421'; // Slovaquie
    case SI = '+386'; // Slovénie
    case SO = '+252'; // Somalie
    case SD = '+249'; // Soudan
    case SS = '+211'; // Soudan du Sud
    case LK = '+94'; // Sri Lanka
    case SE = '+46'; // Suède
    case CH = '+41'; // Suisse
    case SY = '+963'; // Syrie
    case TJ = '+992'; // Tadjikistan
    case TZ = '+255'; // Tanzanie
    case TH = '+66'; // Thaïlande
    case TL = '+670'; // Timor-Leste
    case TG = '+228'; // Togo
    case TO = '+676'; // Tonga
    case TT = '+1-868'; // Trinité-et-Tobago
    case TN = '+216'; // Tunisie
    case TM = '+993'; // Turkménistan
    case TR = '+90'; // Turquie
    case TV = '+688'; // Tuvalu
    case UA = '+380'; // Ukraine
    case UY = '+598'; // Uruguay
    case VU = '+678'; // Vanuatu
    case VA = '+39-06'; // Vatican
    case VE = '+58'; // Venezuela
    case VN = '+84'; // Vietnam
    case YE = '+967'; // Yémen
    case ZM = '+260'; // Zambie
    case ZW = '+263'; // Zimbabwe
}